

service: SNSexperiment

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: eu-west-2
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - sns:SetSMSAttributes
        - sns:Publish
      Resource: '*'


functions:
  sendSMS:
    handler: src/sendSMS.handler
    events: 
      - http:
          path: send-sms
          method: post
          cors: true
 

